- activate.sh
it doesn't work for directories having whitespaces in their names
like `pravj@pravj-HP:~/Desktop/testing/auto env/`
addition in this pull request changes the `IFS` variable on runtime to support whitespaces also, working fine now
there is already an issue for this problem, here #40
can you see this please, @kennethreitz
> now works fine with directories having space in name

- activate.sh
I'm not sure if the syntax is right (I'm not much of a bash scripter), but this should address issue #88.
> Accept 'Y' or 'y' for prompt

- activate.sh
Thank to @keruspe who have pointed me than auto env was sensible to this kind of security issue : http://seclists.org/fulldisclosure/2015/Sep/75
So this patch allow to print hidden characters to be sure autoenv will print evil code if it's hide that way
Before
``` 
denis:~ waxzce$ cd /Users/waxzce/work/tmp/autot
autoenv:
autoenv: WARNING:
autoenv: This is the first time you are about to source /Users/waxzce/work/tmp/autot/.env:
autoenv:
autoenv:     --- (begin contents) ---------------------------------------
autoenv:     #!/bin/bash
autoenv:     echo doing something very nice!
autoenv:     --- (end contents) -----------------------------------------
autoenv:
autoenv: Are you sure you want to allow this? (y/N) ^C
denis:autot waxzce$
```
After
```
denis:~ waxzce$ cd …
```
> Fix security issue using hidden characters

- README.rst
Installing with pip still requires autoenv to be activated.
Fixes #70
> Add autoenv activation to pip installation

- README.rst
Trying to source .env causes I/O errors on smbnetfs mounts; disabling autoenv is an easy answer.
> Add note about temporarily disabling autoenv

- activate.sh
Without this, autoenv thinks a directory is a file and
asks to allow executing it. Autoenv only works for
regular files.
URL: http://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html
> Ignore directory .env, keep searching

- activate.sh
Only activate autoenv when it can find a compatible shasum binary.
I use this version, because homebrew provides my shasum.
> Add support for more hashing functions.

- activate.sh
On my current machine, I currently only have `shasum` installed, not the other binaries. I noticed that `autoenv` wasn't working until I added this line. Looks like a simple copy/paste error.
> Add a missing enable_autoenv if shasum is the only tool available

- README.rst
I think it would be preferable to use the double quote instead of the single for the bash profile addition. The brew install location of autoenv is unlikely to change, and evaluating it once saves about half a second every time bash_profile gets executed.
Please let me know what you think!
> Update README - OSX install directions

- activate.sh
By moving command to change directory in the init function into subshell.
Fix for #141.
> Fix init function to leave $OLDPWD intact

- activate.sh
Since `autoenv` can be use in many shells and by itself used many external commands, so it's better to stick with POSIX standard command options, syntax.
This PR makes many changes to make sure `autoenv` will work in shells which are tested and should be work in any other POSIX compliant shell, system.
> Improvements for portability, security

- README.rst
- activate.sh
Adding a feature that overrides the initial sourcing prompt to create a "silent" switching.
Initialize the `.env` file without asking for permission when an environment variable named `AUTOENV_ASSUME_YES` is set to either `TRUE` or `true`.
> Add an "assume yes" feature

- activate.sh
Bug info https://bugs.debian.org/871816
Another solution might be that those who use zsh put `setopt ALIAS_FUNC_DEF` in `.zshrc`
Fix: https://github.com/kennethreitz/autoenv/issues/173
> Add ALIAS_FUNC_DEF option for zsh

- README.rst
- activate.sh
When used with virtualenv, we can source .env file when entering a directory and activate an environment. But when leaving it, it will not be automatically deactivated. This implementation provides a solution, it will source .env.leave file when leaving working directory. But it also contains issues, such as when entering an environment, we cannot enter subdirectories, because it will be automatically deactivated( We are LEAVING current working directory), but we can also put additional .env file under those directories.
> execute .env.leave file when leaving a directory

- activate.sh
Note: this is exactly the same as #197, but it's a merge from the `tweak-commands` branch, rather than `master`
- more consistently prevent alias expansion across script
- for cases in which alias expansion does not ensure consistent behavior 'command' builtin is used to prevent running user-defined functions rather than the intended builtins
- create parent folder to authfile so `touch` command does not fail
Extra details embedded in the commit messages
> Fix various consistency issues and unnecessary failures #197

- tests/test.sh
This fixes an issue in which the tests wouldn't run due to the use of a Bashism. It also fixes most miscellaneous quoting and command substitution issues
> Improve shell syntax in test suite

- CHANGELOG.md
- README.md
This contains preparation work for the long-awaited `0.3.0` release (the last release was published in 2016!)
If merged, it will close issues pertaining to not creating a release for the latest features to the proper distribution channels. They include:
- MacOS terminal hangs (closes #188, closes #196)
- Brew version out of date (closes #193, closes #180)
- PyPi releases out of date (closes #191, closes #191, closes #187, closes #161)
- Closes #160 as Pip is no longer being recommended as an installation method 
See `CHANGELOG.md` for more specific info about the latest changes since `0.2.1`
Considerations
- Since the Pip package already has a `1.0.0` version, creating a `0.3.0` will do nothing during versionless pip installations of autoenv. Should autoenv be packaged for a different …
> v0.3.0 Release

- README.md
- activate.sh
- tests/test_prompt.bats
Unexpectedly, not allowing to source an `.env` file (by inputing `N`) does not "save". So, every time when `cd`ing into a directory, one must always specify to _not_ `source` the end file.
This PR fixes that by adding a third option `d`/`D` to save that choice into a file called `AUTOENV_NOTAUTH_FILE`.
Adhering to the principle of lease surprise, this file is located in `~` if `AUTOENV_AUTH_FILE` exists there too. Otherwise, it is located in `$XDG_STATE_HOME/autoenv`.
Closes #224
> feat: Add `AUTOENV_NOTAUTH_FILE` to always deny permission to `source` file 

- activate.sh
- tests/test_cd_env_leave.sh
Suppose we `cd` from `a/b` to `a/bz`.
Expected behavior: Invoke `a/b/.env.leave.
Actual behavior prior to this commit: No env-leave is invoked.
The issue is that we are naively checking for string prefixes in `autoenv_leave` in order to determine whether one directory is an ancestor of another. This commit makes the checking slightly less naive by adding a trailing slash. This way, `a/bz/` is not a prefix of `/a/b/`.
> autoenv_leave: Only match prefix on path boundaries

- README.md
> Document `AUTOENV_CUR_*` variables

- activate.sh
These were removed in 55fef32d8a0c61c82be20c34c7f544db40a012d8. I'm undoing the change because I want to be absolutely sure that the new release does not break any existing configurations.
Only the `local` builtin is not escaped. It was not escaped before the removal change.
> Replace references to master branch with main

- activate.sh
This adds the old authorization env prompt that was removed in cdb06270215e574060e20b4be43fb2e6b2626623. Currently, the code path will not be active because `AUTOENV_VIEWER` is set at the top of the file. Before the next release, this old authorization env prompt will be the new default for backwards compatibility.
Some other notes:
- Printing slightly modified to move confusing or extraneous newlines) and, improve readability of title
> Add code path for old authorization env prompt

- activate.sh
Improves check by:
- Using simple string and option condition tests instead of pipes
- Ensure that `has_alias_func_def_enabled` does not have global scope
- Correct misleading comment
Setting this option does not allow autoenv to "Override the cd alias" as the comment suggests. Aliases still have priority, say, when executing `cd`.
What the option does so, is allow Zsh to parse the function definition without erroring. Then, the autoenv cd can be invoked like `\cd`.
Note that with this behavior, Zsh will _silently fail_ setting the autoenv-defined `cd` function. Say, if the user sets `alias cd=something` before sourcing `autoenv.sh`, the autoenv-defined cd function will be called `something` instead.
Another approach is to define functions with the `function` keyword (Bash and Zsh), or …
> Simplify `ALIAS_FUNC_DEF` checks

- activate.sh
- tests/test_variables.bats
The first eval was used to execute code from an earlier `set +o`, so `noclobber` can be enabled. Better is to use `|>`, which is specified by POSIX:
> Output redirection using the '>' format shall fail if the noclobber shell option is set (see the description of [set](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#set) -C) and the file named by the expansion of word exists and is a regular file. Otherwise, redirection using the '>' or ">|" formats shall cause the file whose name results from the expansion of word to be created and opened for output on the designated file descriptor, or standard output if none is specified. If the file does not exist, it shall be created; otherwise, it shall be truncated to be an empty file after being opened.
The second eval was …
> Replaces uses of `eval`

- activate.sh
- tests/test.sh
Now, the following is possible:
```bash
set -u
source ~/autoenv/activate.sh
cd ~/
...
```
> Allow script to run with `nounset` enabled

- activate.sh
By making its default value an empty string, autoenv will now print its old authorization prompt by default. This is so current users of `autoenv` can update without worrying about newfangled UI changes. the README currently already has instructions for setting this variable, so new users get the improved prompt.
> Stop defaulting `AUTOENV_VIEWER` to a non-empty value

- activate.sh
This reverts commit 231791ae885c16380c8cab4a35827ec63c9d6909.
> Revert "Improve internal directory-changing (#247)"
